service: server-cracking-english
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /lookup
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
